# Generated by Django 5.2.17 on 2026-09-08 14:19

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeletedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=140)),
                ("was_published", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PublishRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("refresh", "Refresh complete inventory"),
                            ("publish", "Publish inventory changes"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("ok", "ok"),
                            ("error", "error"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Public product id — used in the storefront URL and every generated file name. Do not change after publishing.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "descriptor",
                    models.CharField(
                        blank=True,
                        help_text="Short catalog-card tagline, e.g. 'Cathedral oval solitaire'.",
                        max_length=200,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="PDP subtitle, e.g. 'Oval Natural Diamond Engagement Ring'.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="PDP 'About the ring' prose."
                    ),
                ),
                (
                    "price_from",
                    models.PositiveIntegerField(default=0, help_text="Whole rupees."),
                ),
                (
                    "shape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Round", "Round"),
                            ("Oval", "Oval"),
                            ("Emerald", "Emerald"),
                            ("Pear", "Pear"),
                            ("Marquise", "Marquise"),
                            ("Cushion", "Cushion"),
                            ("Radiant", "Radiant"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Solitaire", "Solitaire"),
                            ("Hidden Halo", "Hidden Halo"),
                            ("Halo", "Halo"),
                            ("Three Stone", "Three Stone"),
                            ("Side Stone", "Side Stone"),
                            ("Bezel", "Bezel"),
                            ("Contemporary", "Contemporary"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "centre_carat_shown",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Drives the catalog 'centre carat' facet.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Unpublished products are excluded from catalog.json and have no product JSON on storage.",
                    ),
                ),
                (
                    "sort_weight",
                    models.IntegerField(
                        default=0,
                        help_text="Higher sorts first under the 'recommended' order.",
                    ),
                ),
                (
                    "pdp_extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra PDP payload merged verbatim into products/<slug>.json (price_breakup, specifications, trust_line, metals, related, …).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_published_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.category",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["-sort_weight", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="originals/img/")),
                ("alt", models.CharField(blank=True, max_length=250)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="originals/vid/")),
                ("alt", models.CharField(blank=True, max_length=250)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
