# Generated by Django 5.2.17 on 2026-09-08 17:09

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="Stable public id (e.g. 'the-aria'). The storefront takes this token from its URL and fetches products/<id>.json; it also names every generated media folder. Set once — don't change after publishing.",
                max_length=140,
                unique=True,
                verbose_name="Product ID",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=inventory.models._raw_media_path),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(upload_to=inventory.models._raw_media_path),
        ),
    ]
