# Generated by Django 5.2.17 on 2026-09-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_product_slug_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("refresh", "Refresh complete inventory"),
                    ("publish", "Publish inventory changes"),
                    ("rebuild", "Rebuild media from originals"),
                ],
                max_length=12,
            ),
        ),
    ]
