# Generated by Django 5.2.17 on 2026-09-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_publishrun_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media_error',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='media_ready_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='media_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='media_status',
            field=models.CharField(choices=[('idle', 'idle'), ('queued', 'queued'), ('running', 'running'), ('ready', 'ready'), ('error', 'error')], default='idle', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_signature',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_url',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='publishrun',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='running', max_length=12),
        ),
    ]
